### ISSUE TITLE
Update to plugins.json has invalid download link

### ISSUE THREAD

**Issue by lastlink** [creecros/opencomment#4]
https://github.com/kanboard/website/pull/37.
`
"download": "https://github.com/creecros/opencomment/releases/download/0.0.2/CommentOnly-0.0.2.zip",
`
should be
`
"download": "https://github.com/creecros/opencomment/releases/download/0.0.2/opencomment-0.0.2.zip",
`

It also probably should be tested...

**Comment by creecros** [comment]
I'll rename the file, easier.

What's there to test, all you changed was a typo.
